### ISSUE TITLE
MSVC: wxGetApp() used in GUI_Utils.hpp breaks the Windows build after the dark-mode selector

### ISSUE THREAD

**Issue by BenJule** [BenJule/BambuStudio#609]
The Windows Actions build on build/2.8.0-beta fails with C2039/C3861 at GUI_Utils.hpp(205): 'wxGetApp' is not a member of 'Slic3r::GUI'.

The dark-mode selector commit (20a736d18) added a wxEVT_SYS_COLOUR_CHANGED handler in the header whose #ifdef __WINDOWS__ branch calls GUI::wxGetApp().app_config — but GUI_Utils.hpp neither includes GUI_App.hpp (circular) nor sees a declaration. Linux builds never compile that branch, which is why the integration verification (Jenkins build #14) stayed green.

Plan: declare a small free function in the header and implement it in GUI_Utils.cpp, which already includes GUI_App.hpp.
